'use client';

import Link from 'next/link';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { bundleApiOrigin } from '../../lib/links';

type CachedRepo = { repository?: string; git_url?: string; ref?: string; revision?: string; bundle_id?: string };
function api(path: string) { return `${bundleApiOrigin()}${path}`; }
function repoLabel(repo: CachedRepo) { return (repo.repository || repo.git_url || 'Repository').replace(/^https?:\/\//, '').replace(/\.git$/, ''); }

export function RepositoryLauncher() {
  const [repos, setRepos] = useState<CachedRepo[]>([]); const [catalogState, setCatalogState] = useState<'loading' | 'ready' | 'empty' | 'error'>('loading');
  const [url, setUrl] = useState(''); const [ref, setRef] = useState('main'); const [buildState, setBuildState] = useState<'idle' | 'building' | 'error'>('idle'); const [message, setMessage] = useState('');
  useEffect(() => { const controller = new AbortController(); fetch(api('/api/repos'), { headers: { Accept: 'application/json' }, signal: controller.signal }).then((response) => { if (!response.ok) throw new Error('Repository catalog is unavailable right now.'); return response.json(); }).then((body) => { const next = Array.isArray(body?.repositories) ? body.repositories : []; setRepos(next); setCatalogState(next.length ? 'ready' : 'empty'); }).catch((error) => { if (error.name !== 'AbortError') { setCatalogState('error'); setMessage(error instanceof Error ? error.message : 'Repository catalog is unavailable right now.'); } }); return () => controller.abort(); }, []);
  const validUrl = useMemo(() => /^https:\/\/(github\.com|gitlab\.com|bitbucket\.org)\/[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+\/?$/.test(url.trim()), [url]);
  async function submit(event: FormEvent) { event.preventDefault(); if (!validUrl) { setBuildState('error'); setMessage('Use a public HTTPS GitHub, GitLab, or Bitbucket repository URL.'); return; } setBuildState('building'); setMessage(''); try { const response = await fetch(api('/api/build'), { method: 'POST', headers: { 'Content-Type': 'application/json', Accept: 'application/json' }, body: JSON.stringify({ git_url: url.trim(), ref: ref.trim() || 'main' }) }); const body = await response.json(); if (!response.ok || !body?.job_id) throw new Error(body?.error?.message || 'The hosted build could not be started.'); window.location.href = `${bundleApiOrigin()}/?build=${encodeURIComponent(body.job_id)}&repository=${encodeURIComponent(url.trim())}`; } catch (error) { setBuildState('error'); setMessage(error instanceof Error ? error.message : 'The hosted build could not be started.'); } }
  return <section className="launcher" aria-labelledby="launcher-title"><div className="launcher-heading"><span className="page-eyebrow">Choose your starting point</span><h2 id="launcher-title">Bring a repository into focus.</h2><p>Start with a fresh public repository or open a snapshot that has already been indexed by Lachesis.</p></div><div className="launcher-grid"><form className="launcher-card launcher-form" onSubmit={submit}><div className="launcher-card-top"><span className="launcher-index">01</span><span className="launcher-tag">Generate</span></div><h3>Add a repository</h3><p>Paste a public repository URL. Lachesis will build a graph-backed snapshot, then hand you into the first guided flow.</p><label htmlFor="repo-url">Repository URL</label><input id="repo-url" type="url" value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://github.com/owner/repository" autoComplete="url" /><label htmlFor="repo-ref">Branch or revision <span>(optional)</span></label><input id="repo-ref" value={ref} onChange={(event) => setRef(event.target.value)} placeholder="main" /><button className="primary-button launcher-submit" type="submit" disabled={buildState === 'building'}>{buildState === 'building' ? 'Starting build…' : 'Generate map'} <span aria-hidden="true">→</span></button>{buildState === 'error' && <p className="launcher-message" role="alert">{message}</p>}</form><div className="launcher-card cached-card"><div className="launcher-card-top"><span className="launcher-index">02</span><span className="launcher-tag">Cached</span></div><h3>Open a cached repository</h3><p>Use an existing snapshot when you want to read immediately—no rebuild, no waiting.</p>{catalogState === 'loading' && <p className="launcher-status" role="status">Loading indexed repositories…</p>}{catalogState === 'error' && <p className="launcher-status" role="status">{message}</p>}{catalogState === 'empty' && <p className="launcher-status">No public snapshots are available yet. Add a repository to create the first one.</p>}{catalogState === 'ready' && <ul className="cached-list">{repos.map((repo) => repo.bundle_id ? <li key={`${repo.repository}-${repo.revision}`}><Link href={`/flows?${new URLSearchParams({ repository: repoLabel(repo), revision: repo.revision || repo.ref || 'main', bundle: repo.bundle_id }).toString()}`}><span>{repoLabel(repo)}</span><small>{repo.revision ? repo.revision.slice(0, 10) : 'latest'} <b aria-hidden="true">→</b></small></Link></li> : null)}</ul>}</div></div></section>;
}
