import type { RepositorySnapshotView } from './view-model';

/** Deliberately non-live content used until a real Lachesis bundle is supplied. */
export const illustrativeSnapshot: RepositorySnapshotView = {
  provenance: 'illustrative',
  coverageState: 'limited',
  repository: 'Suricata',
  revision: '8f4c1b2',
  language: 'C',
  coverageScope: 'illustrative repository slice',
  indexedNodes: 12486,
  includedNodes: 12486,
  limitations: ['Illustrative fixture; not a live Suricata checkout.', 'Region placement is editorial.'],
  regions: [
    { id: 'input', label: 'Packet input', summary: 'Accepts raw packets and establishes the first framing boundary.', path: 'src/source', nodeCount: 34, metricLabel: '34 illustrative files', role: 'entry', outputs: ['raw frame + capture metadata'], downstream: ['decode'], children: [{ label: 'Capture adapters', summary: 'Bring bytes into the engine.' }, { label: 'Packet buffers', summary: 'Hold the current frame window.' }], structures: ['Packet buffer'], anchor: { id: 'capture', label: 'ReceivePacket()', file: 'src/source/receive.c', line: 74 } },
    { id: 'decode', label: 'Packet decode', summary: 'Peels Ethernet, IP, and transport headers while validating lengths at every layer.', path: 'src/decode', nodeCount: 62, metricLabel: '62 illustrative files', role: 'runtime', inputs: ['raw frame + capture metadata'], outputs: ['decoded headers + transport payload'], upstream: ['input'], downstream: ['core'], children: [{ label: 'Layer decoders', summary: 'Ethernet → IP → TCP/UDP.' }, { label: 'Length guards', summary: 'Reject truncated or inconsistent headers.' }], structures: ['Packet header fields', 'Validated payload window'], anchor: { id: 'decode', label: 'DecodeEthernet()', file: 'src/decode/decode-ethernet.c', line: 42 } },
    { id: 'core', label: 'Flow + stream state', summary: 'Groups packets into bidirectional flows and reassembles TCP data for downstream parsers.', path: 'src/flow', nodeCount: 118, metricLabel: '118 illustrative files', role: 'runtime', inputs: ['decoded packet'], outputs: ['packet attached to Flow', 'reassembled stream data'], upstream: ['decode'], downstream: ['protocols'], children: [{ label: 'Flow manager', summary: 'Creates, looks up, compares, and expires flows.' }, { label: 'TCP stream engine', summary: 'Reassembles out-of-order segments.' }], structures: ['Packet', 'Flow', 'TCP stream state'], anchor: { id: 'flow', label: 'FlowSetupPacket()', file: 'src/flow/flow.c', line: 214 } },
    { id: 'protocols', label: 'Application protocols', summary: 'Detects the protocol carried by a flow and routes bytes to the matching parser.', path: 'src/app-layer', nodeCount: 186, metricLabel: '186 illustrative files', role: 'runtime', inputs: ['reassembled stream data'], outputs: ['normalized protocol transactions'], upstream: ['core'], downstream: ['detect'], children: [{ label: 'Protocol detection', summary: 'Chooses the parser family.' }, { label: 'TLS / SSL', summary: 'Tracks handshake and record state.' }, { label: 'DNP3, SMTP, FTP', summary: 'Reconstructs application messages.' }], structures: ['Application parser state', 'Transaction records'], anchor: { id: 'parser', label: 'AppLayerParserParse()', file: 'src/app-layer.c', line: 301 } },
    { id: 'detect', label: 'Detection engine', summary: 'Runs protocol-aware signatures over packets, flows, and transactions.', path: 'src/detect', nodeCount: 227, metricLabel: '227 illustrative files', role: 'fanout', inputs: ['normalized protocol transactions'], outputs: ['matches + alert candidates'], upstream: ['protocols'], downstream: ['output'], children: [{ label: 'Prefilter', summary: 'Narrows the candidate rule set.' }, { label: 'Rule engine', summary: 'Evaluates protocol-aware signatures.' }, { label: 'Datasets', summary: 'Provides shared lookup sets.' }], structures: ['Signature tables', 'Detection context'], anchor: { id: 'signature', label: 'DetectRunTx()', file: 'src/detect/detect.c', line: 411 } },
    { id: 'matcher', label: 'Pattern matching', summary: 'Scans payloads against many rule patterns in one pass before expensive matching.', path: 'src/util-mpm', nodeCount: 91, metricLabel: '91 illustrative files', role: 'fanout', upstream: ['detect'], downstream: ['detect'], children: [{ label: 'Multi-pattern matcher', summary: 'Builds and runs the matching automaton.' }], anchor: { id: 'mpm', label: 'SCACCreateDeltaTable()', file: 'src/util-mpm-ac.c', line: 155 } },
    { id: 'output', label: 'Alerts + output', summary: 'Serializes alerts, flow records, and protocol telemetry for configured consumers.', path: 'src/output', nodeCount: 74, metricLabel: '74 illustrative files', role: 'output', inputs: ['matches + alert candidates', 'flow and transaction records'], outputs: ['alerts + telemetry'], upstream: ['detect'], children: [{ label: 'Alert output', summary: 'Emits detection results.' }, { label: 'EVE logging', summary: 'Serializes JSON telemetry.' }], structures: ['Alert record', 'Telemetry event'], anchor: { id: 'output', label: 'OutputTxLogCallLoggers()', file: 'src/output/output.c', line: 63 } },
    { id: 'boot', label: 'Initialization', summary: 'Builds the signature language and wires the engine after configuration load.', path: 'src/runmodes', nodeCount: 29, metricLabel: '29 illustrative files', role: 'boot', children: [{ label: 'Signature registration', summary: 'Registers rule keywords.' }, { label: 'Post-config setup', summary: 'Connects runtime operations.' }], anchor: { id: 'boot', label: 'PostConfLoadedSetup()', file: 'src/runmodes/runmodes.c', line: 92 } },
  ],
};
