import Link from 'next/link';
import type { Metadata } from 'next';
import { DocsShell, EvidenceNote, PageIntro } from '../../components/DocsShell';
import { illustrativeSnapshot } from '../../../lib/view-model';

export function generateStaticParams() { return illustrativeSnapshot.regions.map((region) => ({ region: region.id })); }

export async function generateMetadata({ params }: { params: Promise<{ region: string }> }): Promise<Metadata> {
  const { region: regionId } = await params;
  const region = illustrativeSnapshot.regions.find((item) => item.id === regionId);
  return region ? { title: `${region.label} · ${illustrativeSnapshot.repository} architecture`, description: `${region.summary} Read the ${region.label} chapter in Design Map before opening the source.` } : { title: 'Architecture region · Design Map' };
}

export default async function RegionPage({ params, searchParams }: { params: Promise<{ region: string }>; searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const { region: regionId } = await params;
  const query = await searchParams;
  const bundle = typeof query.bundle === 'string' ? query.bundle : undefined;
  const repository = typeof query.repository === 'string' ? query.repository : undefined;
  const revision = typeof query.revision === 'string' ? query.revision : undefined;
  const region = illustrativeSnapshot.regions.find((item) => item.id === regionId);
  if (!region) return <DocsShell active="/architecture"><div className="doc-page region-page"><Link className="back-link" href="/architecture">← Architecture</Link><PageIntro title={regionId} snapshot={illustrativeSnapshot}>This region is not present in the illustrative index. It may belong to a different graph-backed snapshot or an expired link.</PageIntro><section className="map-state-panel"><span className="map-state-label">Region context unavailable</span><h2>Open the snapshot that contains this region.</h2><p>The chapter cannot invent responsibility, neighbors, or anchors without the matching repository revision. Return to the map or continue into Lachesis with the context you already have.</p><Link className="primary-button" href={`/explore?${new URLSearchParams({ region: regionId, ...(repository ? { repository } : {}), ...(revision ? { revision } : {}), ...(bundle ? { bundle } : {}) }).toString()}`}>Continue to Lachesis <span aria-hidden="true">↗</span></Link></section><EvidenceNote>Unknown regions are kept as recoverable links rather than treated as verified architecture facts.</EvidenceNote></div></DocsShell>;
  const neighbors = [...(region.upstream ?? []), ...(region.downstream ?? [])].map((id) => illustrativeSnapshot.regions.find((item) => item.id === id)).filter(Boolean);
  return <DocsShell active="/architecture"><div className="doc-page region-page"><Link className="back-link" href="/architecture">← Architecture</Link><PageIntro title={region.label} snapshot={illustrativeSnapshot}>{region.summary} This chapter keeps the design-level responsibility in view before you open the implementation.</PageIntro><div className="region-meta"><div><span>Footprint</span><strong>{region.metricLabel}</strong></div><div><span>Repository path</span><code>{region.path}</code></div><div><span>Role</span><strong>{region.role ?? 'runtime region'}</strong></div></div><section className="region-section"><h2>What this region owns</h2><p>{region.summary}</p>{region.children && <ul className="region-children">{region.children.map((child) => <li key={child.label}><strong>{child.label}</strong><span>{child.summary}</span>{child.anchor && <code>{child.anchor}</code>}</li>)}</ul>}</section><section className="region-section"><h2>How it connects</h2>{neighbors.length ? <ul className="neighbor-list">{neighbors.map((neighbor) => <li key={neighbor!.id}><Link href={`/architecture/${neighbor!.id}`}><span>{neighbor!.label}</span><small>{region.downstream?.includes(neighbor!.id) ? 'downstream' : 'upstream'} →</small></Link></li>)}</ul> : <p>This projection has no neighboring region metadata at this level.</p>}</section><section className="region-section"><h2>Open the anchor</h2><p>{region.anchor ? <><code>{region.anchor.label}</code> lives at <code>{region.anchor.file}:{region.anchor.line}</code>. Lachesis can show its callers, callees, and exact source context.</> : 'This region has no anchor in the current projection.'}</p><Link className="primary-button" href={`/explore?${new URLSearchParams({ repository: illustrativeSnapshot.repository, revision: illustrativeSnapshot.revision, region: region.id, label: region.label, anchor: region.anchor?.label ?? region.label }).toString()}`}>Prepare Lachesis handoff <span aria-hidden="true">↗</span></Link></section><EvidenceNote>This region chapter is illustrative prototype content. Placement and descriptions should be regenerated from the selected graph-backed snapshot.</EvidenceNote></div></DocsShell>;
}
